### ISSUE TITLE
Error when getting and setting a key

### ISSUE THREAD

**Issue by ScottSmudger** [kirillpisarev/react-native-key-value-storage#1]
Hi,

I am getting these errors when setting and getting a key/value pair
Error setting key: [TypeError: undefined is not an object (evaluating '_reactNativeKeyValueStorage.default.set')]

Error getting key: [TypeError: undefined is not an object (evaluating '_reactNativeKeyValueStorage.default.get')]

Any recommendations would be great
Thanks

**Comment by kirillpisarev** [comment]
Seems like you didn't link the native code. Make sure you executed `react-native link react-native-key-value-storage` after installing the lib.
